name: Docker Image CI

on:
  workflow_call:
    inputs:
      IMAGE:
        description: "Docker image name"
        type: string
        required: true
      SERIAL:
        description: "Zone serial number"
        type: string
        required: true
      PUSH:
        description: "Actually push the image"
        type: boolean
        required: false
        default: false

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "v${{ inputs.SERIAL }}"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ inputs.IMAGE }}
          tags: |
            # from input SERIAL
            type=raw,value=v${{ inputs.SERIAL }}
            # generate latest
            # type=raw,value=latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - run: echo "::notice::${{ secrets.DOCKERHUB_USERNAME == 'mrtux' }}"

      - name: Login to DockerHub
        if: inputs.PUSH
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: ${{ inputs.PUSH }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
