name: Main Workflow

on:
  push:
    branches:
      - 'main'


jobs:
  verify-structure:
    name: "Verify repository structure"
    concurrency: verify
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello World
      run: echo "Hello world."

  verify-zone:
    name: "Verify zone syntax"
    concurrency: verify
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello World
      run: echo "Hello world."

  update-serial:
    name: "Update serial number"
    needs:
    - verify-structure
    - verify-zone
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello World
      run: echo "Hello world."

  build-image:
    name: "Build Docker image"
    needs:
    - update-serial
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello World
      run: echo "Hello world."
