name: Main Workflow

on:
  push:
    branches:
      - 'main'


jobs:
  validate-structure:
    name: "Validate repository structure"
    uses: ./.github/workflows/validate-structure.yml

  validate-zone:
    name: "Validate zone syntax"
    uses: ./.github/workflows/validate-zone.yml

  update-serial:
    name: "Update serial number"
    needs:
    - validate-structure
    - validate-zone
    uses: ./.github/workflows/update-serial.yml

  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::notice::${{ secrets.DOCKERHUB_USERNAME == 'mrtux' }}"

  build-image:
    name: "Build Docker image"
    needs:
    - update-serial
    if: needs.update-serial.outputs.serial
    uses: ./.github/workflows/docker-image.yml
    with:
      IMAGE: ffmd/bind9-playground
      SERIAL: ${{ needs.update-serial.outputs.serial }}
      PUSH: true
    secrets: inherit
