name: Main Workflow

on:
  push:
    branches:
      - 'main'


jobs:
  validate-structure:
    name: "Validate repository structure"
    concurrency: validate
    uses: ./.github/workflows/validate-structure.yml

  validate-zone:
    name: "Validate zone syntax"
    concurrency: validate
    uses: ./.github/workflows/validate-zone.yml

  update-serial:
    name: "Update serial number"
    needs:
    - validate-structure
    - validate-zone
    uses: ./.github/workflows/update-serial.yml

  build-image:
    name: "Build Docker image"
    needs:
    - update-serial
    runs-on: ubuntu-latest
    steps:
    - name: Print Impl Warning
      run: echo "::warning::Not implemented."
